#The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
#
#1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
#
#Let us list the factors of the first seven triangle numbers:
#
#     1: 1
#     3: 1,3
#     6: 1,2,3,6
#    10: 1,2,5,10
#    15: 1,3,5,15
#    21: 1,3,7,21
#    28: 1,2,4,7,14,28
#
#We can see that 28 is the first triangle number to have over five divisors.
#
#What is the value of the first triangle number to have over five hundred divisors?
prastevila = [2,3,5,7,11,13,17]

def stevDeliteljev(tabelaFaktorjev):
    tabelaPosameznihFaktorjev = 0
    prod = 1

    for prastev in prastevila:
        prod *= tabelaFaktorjev.count(prastev) +1 
    return prod

def fakotriziraj(stevilo):
    faktorji = []
    if stevilo in prastevila:
        return faktorji + [stevilo]
    for prastev in prastevila:
        if stevilo % prastev == 0:
            return faktorji + fakotriziraj(prastev) + fakotriziraj(stevilo//prastev)
    return [stevilo]
        
triangleNum = 1
naravnoStevilo = 1

while True:
    faktorji = fakotriziraj(triangleNum)
    if stevDeliteljev(faktorji) > 500:
        break
    naravnoStevilo += 1
    triangleNum += naravnoStevilo
print(triangleNum)